version: '3'

services:

  server:
    build: .
    container_name: flask
    ports:
      - "24579:24579"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest

    ports:
      - "3307:3306"

    container_name: flask_db_mysql

    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=flask_restful
